/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Directives': RouteRecordInfo<'/Directives', '/Directives', Record<never, never>, Record<never, never>>,
    '/Interpolation': RouteRecordInfo<'/Interpolation', '/Interpolation', Record<never, never>, Record<never, never>>,
    '/WeekThree/DayOne/ExerciseThreeOne': RouteRecordInfo<'/WeekThree/DayOne/ExerciseThreeOne', '/WeekThree/DayOne/ExerciseThreeOne', Record<never, never>, Record<never, never>>,
    '/WeekThree/DayOne/ExerciseThreeThree': RouteRecordInfo<'/WeekThree/DayOne/ExerciseThreeThree', '/WeekThree/DayOne/ExerciseThreeThree', Record<never, never>, Record<never, never>>,
    '/WeekThree/DayOne/ExerciseThreeTwo': RouteRecordInfo<'/WeekThree/DayOne/ExerciseThreeTwo', '/WeekThree/DayOne/ExerciseThreeTwo', Record<never, never>, Record<never, never>>,
  }
}
