/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/ActivatedLifeHook': RouteRecordInfo<'/ActivatedLifeHook', '/ActivatedLifeHook', Record<never, never>, Record<never, never>>,
    '/ButtonComponentExample': RouteRecordInfo<'/ButtonComponentExample', '/ButtonComponentExample', Record<never, never>, Record<never, never>>,
    '/ClassStyleBinding': RouteRecordInfo<'/ClassStyleBinding', '/ClassStyleBinding', Record<never, never>, Record<never, never>>,
    '/Components': RouteRecordInfo<'/Components', '/Components', Record<never, never>, Record<never, never>>,
    '/ComponentVModel': RouteRecordInfo<'/ComponentVModel', '/ComponentVModel', Record<never, never>, Record<never, never>>,
    '/Directives': RouteRecordInfo<'/Directives', '/Directives', Record<never, never>, Record<never, never>>,
    '/Interpolation': RouteRecordInfo<'/Interpolation', '/Interpolation', Record<never, never>, Record<never, never>>,
    '/LifecycleHooks': RouteRecordInfo<'/LifecycleHooks', '/LifecycleHooks', Record<never, never>, Record<never, never>>,
    '/TabbedTimer': RouteRecordInfo<'/TabbedTimer', '/TabbedTimer', Record<never, never>, Record<never, never>>,
    '/UnmountedComponent': RouteRecordInfo<'/UnmountedComponent', '/UnmountedComponent', Record<never, never>, Record<never, never>>,
    '/WeekFour/DayTwo/ExerciseOne': RouteRecordInfo<'/WeekFour/DayTwo/ExerciseOne', '/WeekFour/DayTwo/ExerciseOne', Record<never, never>, Record<never, never>>,
    '/WeekFour/DayTwo/ExerciseThree': RouteRecordInfo<'/WeekFour/DayTwo/ExerciseThree', '/WeekFour/DayTwo/ExerciseThree', Record<never, never>, Record<never, never>>,
    '/WeekFour/DayTwo/ExerciseTwo': RouteRecordInfo<'/WeekFour/DayTwo/ExerciseTwo', '/WeekFour/DayTwo/ExerciseTwo', Record<never, never>, Record<never, never>>,
    '/WeekThree/DayFour/ExerciseOne': RouteRecordInfo<'/WeekThree/DayFour/ExerciseOne', '/WeekThree/DayFour/ExerciseOne', Record<never, never>, Record<never, never>>,
    '/WeekThree/DayFour/ExerciseTwo': RouteRecordInfo<'/WeekThree/DayFour/ExerciseTwo', '/WeekThree/DayFour/ExerciseTwo', Record<never, never>, Record<never, never>>,
    '/WeekThree/DayOne/ExerciseOne': RouteRecordInfo<'/WeekThree/DayOne/ExerciseOne', '/WeekThree/DayOne/ExerciseOne', Record<never, never>, Record<never, never>>,
    '/WeekThree/DayOne/ExerciseThree': RouteRecordInfo<'/WeekThree/DayOne/ExerciseThree', '/WeekThree/DayOne/ExerciseThree', Record<never, never>, Record<never, never>>,
    '/WeekThree/DayOne/ExerciseTwo': RouteRecordInfo<'/WeekThree/DayOne/ExerciseTwo', '/WeekThree/DayOne/ExerciseTwo', Record<never, never>, Record<never, never>>,
    '/WeekThree/DayThree/ExerciseOne': RouteRecordInfo<'/WeekThree/DayThree/ExerciseOne', '/WeekThree/DayThree/ExerciseOne', Record<never, never>, Record<never, never>>,
    '/WeekThree/DayThree/ExerciseTwo': RouteRecordInfo<'/WeekThree/DayThree/ExerciseTwo', '/WeekThree/DayThree/ExerciseTwo', Record<never, never>, Record<never, never>>,
    '/WeekThree/DayTwo/ExerciseOne': RouteRecordInfo<'/WeekThree/DayTwo/ExerciseOne', '/WeekThree/DayTwo/ExerciseOne', Record<never, never>, Record<never, never>>,
    '/WeekThree/DayTwo/ExerciseThree': RouteRecordInfo<'/WeekThree/DayTwo/ExerciseThree', '/WeekThree/DayTwo/ExerciseThree', Record<never, never>, Record<never, never>>,
    '/WeekThree/DayTwo/ExerciseTwo': RouteRecordInfo<'/WeekThree/DayTwo/ExerciseTwo', '/WeekThree/DayTwo/ExerciseTwo', Record<never, never>, Record<never, never>>,
  }
}
